spring:
  datasource:
    username: root
    password: 123456

    url: jdbc:mysql://127.0.0.1:3306/coordinate?serverTimezone=GMT

  driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8082
hibernate:
  ddl-auto: update